# Generated by Django 3.2.18 on 2023-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='whishlist_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
